### PR TITLE
Add linting script and lint files

### PR DESCRIPTION
**Pull request by martinratinaud**
Fixes https://github.com/ambanum/OpenTermsArchive/issues/833

### CODE REVIEW

**Review by MattiSG — CHANGES_REQUESTED** [review]
Failing linting should fail CI.

**Comment by martinratinaud** [comment]
It will when `json_lint` branch is merged on master on OTA core

**Comment by MattiSG** [comment]
@Amustache @mvidonne following minor formatting issues that were identified across declarations and that could sometimes lead to failures, we have now added a validation step for formatting 🙂
This feature can be used locally by running `npm run lint`, and will be tested automatically in CI.
This PR enables this feature and updates all declarations to comply with the new mandated format.
Can you please confirm that this is okay for you by reviewing this pull request and approving it? 🙂

**Review by MattiSG — CHANGES_REQUESTED** [review]
@martinratinaud https://github.com/ambanum/OpenTermsArchive/pull/841 has been merged and I re-run all jobs, but CI still passes.

**Comment by martinratinaud** [comment]
> @martinratinaud [ambanum/OpenTermsArchive#841](https://github.com/ambanum/OpenTermsArchive/pull/841) has been merged and I re-run all jobs, but CI still passes.

@MattiSG not usre to understand what you mean.

I ran the linting on all files in this repo so it is normal that CI passes, I believe this should be merged and all subsequent changes or addition will benefit from the linting check.

**Review by Amustache — APPROVED** [review]
Excellente idea, thank you!

**Comment by MattiSG** [comment]
> I ran the linting on all files in this repo so it is normal that CI passes

Yes, that's what I realised afterwards, see my [review dismissal](https://github.com/OpenTermsArchive/dating-declarations/pull/92#event-6599550758) 😉

**Pull request merged**
