### PR TITLE
Update happn.json

### PR DESCRIPTION
**Pull request by mvidonne**
selectors updated

### CODE REVIEW

**Review by clementbiron — APPROVED** [review]
Hi Marie Pierre,

I've made several changes based on your suggestion, particularly because the Terms of Service and Privacy Policy urls have changed.

**Comment by clementbiron** [comment]
The CI tests do not pass and return a 403 error.

Let's try again in a few days.

**Comment by MattiSG** [comment]
Is this 403 also happening locally, or only in CI?

**Comment by clementbiron** [comment]
Both.

**Comment by clementbiron** [comment]
Still stuck on an 403 error today.

**Comment by clementbiron** [comment]
After discussion with the core team, we decided to bypass the tests in such cases. The documentation will be updated accordingly to explain when and why we can do that.

**Pull request merged**
